### ISSUE TITLE
Getting errors running npm install with newer versions of npm

### ISSUE THREAD

**Issue by ckapopoulos** [Vikasg7/line-reader-browser#1]
node.js: 16.14.0
npm: 8.3.1

`npm ERR! command C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\user\AppData\Local\npm-cache --prefer-
offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > thenForEach@0.0.7 install
npm ERR! > node_modules/.bin/tsc
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! 'node_modules' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! npm ERR! code 1
`

**Comment by Vikasg7** [comment]
@ckapopoulos here is simplified version.  
```html
<!DOCTYPE html>
<html>
<body>
  <input type="file" id="input" />

  <script>
    async function* ReadLines(file) {
      const reader = file.stream().getReader()
      const utf8Decoder = new TextDecoder("utf-8")
      let chunk
      let lastLine = ""
      do {
        let { value: chunk }  = await reader.read()
        const lines = (lastLine + utf8Decoder.decode(chunk, { stream: true })).split(/\r?\n|\r(?!\n)/)
        lastLine = lines.pop()
        for (let line of lines) yield line;
      } while (chunk)
      if (lastLine) yield lastLine;
    }

    document.getElementById('input').addEventListener('change', async function (e) {
      let file = document.getElementById('input').files[0];
      for await (let line of ReadLines(file)) console.log(line);
    });
  </script>
</body>
</html>
```

**Comment by Vikasg7** [comment]
@ckapopoulos I also fixed the build error in the `thenForEach` lib, `line-reader-browser` should install fine now. However, I believe that, though this lib gets the job done, it is overkill and very badly written. So I suggest you use the snippet above for your needs.
